### PR TITLE
Fixed bug where parentless frames were reported as non existent

### PR DESCRIPTION
**Pull request by gstavrinos**

### CODE REVIEW

**Comment by gstavrinos** [comment]
Any comments on this?

**Comment by tfoote** [comment]
Can you clarify what you are seeing and what you expect to see. Your pull request is failing several unit tests related to this function.

**Comment by gstavrinos** [comment]
Hello Tully, thanks for replying. 

In a tf tree like this:
odom_root


The rospy frameExists always returns false for the root of the tf tree (odom). This started after the latest commits in geometry. (I noticed it after an upgrade through apt)

**Comment by tfoote** [comment]
As documented in the comment this function is specific one for backwards compatibility. It's closely connected to the internal logic where the parents are not explicitly recorded just referred to. I think you simply want to use the [`allFramesAsString` method](https://github.com/ros/geometry/blob/indigo-devel/tf/src/tf/listener.py#L59)

You can see the different behavior is specifically called out in the [unit tests](https://github.com/ros/geometry/blob/indigo-devel/tf/test/testPython.py#L50-L58).

**Pull request closed without merging**
