### PR TITLE
[melodic] use modern c++11 for portability.

### PR DESCRIPTION
**Pull request by seanyen**
This is a follow up of #182.

* Default to C++14 in `CMakeLists.txt`.
* Use `<ctime>` `<cstdlib>` for random number generation.
* Use `<cmath>` for `NAN` usage.
* Use `<chrono>` and `<thread>` for sleep.
* Conditionally undefine `NO_ERROR` to avoid symbol redefinition by `Windows` headers.

### CODE REVIEW

**Comment by seanyen** [comment]
@tfoote This is ready for review and merge. Thanks.

**Comment by seanyen** [comment]
@tfoote Friendly ping.

**Comment by seanyen** [comment]
@tfoote any chances to review this one as well? :)

**Comment by tfoote** [comment]
@ros-pull-request-builder retest this please

**Review by tfoote — APPROVED** [review]
Sorry the noetic test failures weren't retriggering because it's on a different branch now.

**Pull request merged**
