### PR TITLE
Add deprecation warning to tf view_frames.

### PR DESCRIPTION
**Pull request by lauralindzey**
As discussed in #201

### CODE REVIEW

**Comment by lucbettaieb** [comment]
+1 @tfoote

**Comment by lucbettaieb** [comment]
+1 @mikeferguson maybe?

**Comment by lianghongzhuo** [comment]
+1

**Review by tfoote — APPROVED** [review]

**Comment by wxmerkt** [comment]
Thank you @lauralindzey and @tfoote. Can we have a release with #216 and #217 please?

**Pull request merged**
