### PR TITLE
[melodic] updated library install for better portability.

### PR DESCRIPTION
**Pull request by seanyen**
This pull request is to install the library to the correct location for Windows.

The change adheres with the catkin guide:
https://docs.ros.org/api/catkin/html/howto/format1/building_libraries.html

### CODE REVIEW

**Comment by seanyen** [comment]
@tfoote This is ready for review and merge. Thanks!

**Comment by seanyen** [comment]
@tfoote Friendly ping.

**Comment by seanyen** [comment]
@tfoote Following up. Should I retarget it to `noetic`?

**Review by tfoote — APPROVED** [review]

**Comment by tfoote** [comment]
sorry for the delay

**Pull request merged**
