### PR TITLE
fixed Eigen-KDL 3D Vector conversion functions

### PR DESCRIPTION
**Pull request by fevb**
Fixed errors in the Eigen-KDL + KDL-Eigen vector conversion functions.

### CODE REVIEW

**Comment by tfoote** [comment]
Thanks for the catch. That's a bad copy and paste error. 

Unfortunately this being an API changing patch and Hydro being well out I will plan to merge this for indigo cycle.

**Comment by wjwwood** [comment]
+1 for Indigo merge.

**Comment by fevb** [comment]
Sounds good!

**Comment by tfoote** [comment]
merged into indigo-devel

**Pull request closed without merging**
