### PR TITLE
fix for issue in getAngleShortestPath()

### PR DESCRIPTION
**Pull request by MichaelKorn**
Testing squared norm for <0 does not make any sense. In Addition giving the range of the return values is a great help to understand the descriptions.

### CODE REVIEW

**Comment by tfoote** [comment]
That looks reasonable. This is a fork of the bullet physics library and we'd prefer not to diverge. Could you submit this upstream to them: https://github.com/bulletphysics/bullet3/blob/master/src/LinearMath/btQuaternion.h#L429 and if it's accepted we can merge it back. I'd rather not diverge if possible.

**Comment by MichaelKorn** [comment]
Sure, I understand. I created a pull request: https://github.com/bulletphysics/bullet3/pull/577

**Comment by MichaelKorn** [comment]
The Pull request was merged.

**Comment by tfoote** [comment]
Great thanks for following up there.

**Pull request merged**
