### PR TITLE
conversions: Add return-by-value wrappers.

### PR DESCRIPTION
**Pull request by de-vri-es**
This pull request adds wrappers for the existing conversion functions that take only one argument and return the result by value. Right now they have the same names as the original functions (but see below). They are defined in a separate header.

Currently compiling code should not be affected even if some other header pulls in the by-value conversions since these functions have a different signature from the originals.

In my opinion the resulting code is much easier to read:

```
Eigen::Vector3d vector = vectorKDLtoEigen(kdl_vector);
```

VS

```
Eigen::Vector3d vector;
vectorKDLtoEigen(kdl_vector, vector);
```

The first snippet shows in a single look that `vector` is being set while for the second snippet you need to really read what the code says.

Additionally it allows passing the converted values directly to functions and initializer lists:

```
doSomething(vectorKDLtoEigen(position));

class Foo : public Bar {
public:
    // Can't even make a local variable here as workaround, need a return-by-value conversion function.
    Foo(Eigen::Vector3d const & position) : Bar(vectorEigenToKDL(position) {}
}
```
#### Affine3d

I didn't add a by-value conversion to `Eigen::Affine3d` because you can't overload on return type, and `Isometry3d` is implicitly convertible to `Affine3d`. So there is no need for a conversion by-value to `Affine3d` anyway.
#### Naming

I'm not sure on the naming of the functions yet. For conversion functions you don't really need the name to state what goes in, only what comes out. So I was thinking about names like

```
Eigen::Vector3d toEigenVector3d(const KDL::Vector &);
Eigen::Vector3d toEigenVector3d(const geometry_msgs::Point &);
Eigen::Vector3d toEigenVector3d(const geometry_msgs::Vector3 &);

KDL::Vector3 toKDLVector(const Eigen::Vector3d &);
geometry_msgs::Point toMsgPoint(const Eigen::Vector3d &);
geometry_msgs::Vector3 toMsgVector3(const Eigen::Vector3d &);
```

Converting twist and wrench values are both converted to a 6 dimensional vector in Eigen though, so would those get the same name then?

Thoughts on naming the functions are welcome.

### CODE REVIEW

**Comment by de-vri-es** [comment]
Any thoughts?

**Comment by tfoote** [comment]
The change overall is reasonable, however this API is deprecated and it's recommended to use tf2 which has a more complete conversion API. http://wiki.ros.org/tf2/Tutorials/Migration/DataConversions

I'm a little hesitant to add new API when there's a new API that already exists and can do most of what you want. (note the convert method returns by reference which allows chaining expressions on one line.)

I'd rather work to extend that API to match your use cases instead of extending this version of the API.

**Comment by de-vri-es** [comment]
I see, the new API looks much more usable. Although it is disappointing to see that again `Eigen::Affine3d` is used to represent poses rather than `Eigen::Isometry3d`.

Is `tf` truly deprecated / end-of-life in favor of `tf2`? If so, I agree this PR can be closed without merging.

**Comment by tfoote** [comment]
yeah, the internals of tf are entirely removed and tf2 is used under the hood. Due to the amount of code using it we're not tocking `tf` actively. But we're pushing all new development onto geometry2. 

For tf2_eigen a PR to add support converting a transform into an`Eigen::Isometry3d`  would be welcome.  The old one was kept to be as little disruptive as possible. But there's no reason to not add the other one for those who prefer the stricter type now that it's available.

**Pull request closed without merging**
