### PR TITLE
using TimeStamp and FrameId in message filter

### PR DESCRIPTION
**Pull request by bricerebsamen**
this allows to use tf::MessageFilter with pcl::PointCloud<T>

Connects to #55

### CODE REVIEW

**Comment by bricerebsamen** [comment]
@tfoote I'm planning to migrate my code to tf2. Should I port this change into tf2?

**Comment by tfoote** [comment]
That would be great. I'm trying to go through my geometry issues this week. That would be a great thing to add to tf2 as well.

**Comment by tfoote** [comment]
Reviewing this diff, I'd like to have it still assert the slightly more loose condition that it either has a header or has both fields needed for the header.

**Comment by bricerebsamen** [comment]
that'd be great. But there is no `HasStamp` or `HasFrameId` in `message_traits`. I can create it though...

**Pull request merged**
