### PR TITLE
remove .hgignore

### PR DESCRIPTION
**Pull request by tfoote**
We're using git

### CODE REVIEW

**Comment by tfoote** [comment]
@ros-pull-request-builder retest this please

**Comment by tfoote** [comment]
@ros-pull-request-builder retest this please

**Comment by tfoote** [comment]
@ros-pull-request-builder retest this please

**Comment by tfoote** [comment]
@ros-pull-request-builder retest this please

**Comment by tfoote** [comment]
@ros-pull-request-builder retest this please

**Comment by tfoote** [comment]
@ros-pull-request-builder retest this please

**Comment by tfoote** [comment]
@ros-pull-request-builder retest this please

**Comment by tfoote** [comment]
@ros-pull-request-builder retest this please

**Comment by nuclearsandwich** [comment]
@ros-pull-request-builder retest this please

**Comment by nuclearsandwich** [comment]
@ros-pull-request-builder retest this please

**Comment by nuclearsandwich** [comment]
@ros-pull-request-builder retest this please

**Comment by nuclearsandwich** [comment]
@ros-pull-request-builder retest this please

**Comment by nuclearsandwich** [comment]
@ros-pull-request-builder retest this please

**Comment by nuclearsandwich** [comment]
@ros-pull-request-builder retest this please

**Comment by nuclearsandwich** [comment]
@ros-pull-request-builder retest this please.

**Comment by nuclearsandwich** [comment]
@ros-pull-request-builder you know what to do! Retest this please.

**Comment by nuclearsandwich** [comment]
There are two commit statuses, `default` and `jenkins` which can be ignored for this PR. They were set during testing.

**Pull request merged**
