### PR TITLE
Fix build error in tf_conversions with orocos_kdl dependency

### LINKED ISSUE #45: Undefined symbol during link of tf_conversions
Doing a build from source against today's version of tf_conversions, I'm getting this linker error:

```
Scanning dependencies of target tf_conversions
[ 50%] [100%] Building CXX object CMakeFiles/tf_conversions.dir/src/tf_kdl.cpp.o
Building CXX object CMakeFiles/tf_conversions.dir/src/tf_eigen.cpp.o
Linking CXX shared library /Users/tlau/ros/devel_isolated/tf_conversions/lib/libtf_conversions.dylib
Undefined symbols for architecture x86_64:
  "KDL::Vector::Normalize(double)", referenced from:
      KDL::Rot(KDL::Vector const&) in tf_kdl.cpp.o
  "KDL::Rotation::Quaternion(double, double, double, double)", referenced from:
      tf::quaternionTFToKDL(tf::Quaternion const&, KDL::Rotation&) in tf_kdl.cpp.o
  "KDL::operator*(KDL::Rotation const&, KDL::Rotation const&)", referenced from:
      KDL::operator*(KDL::Frame const&, KDL::Frame const&) in tf_kdl.cpp.o
      KDL::addDelta(KDL::Rotation const&, KDL::Vector const&, double) in tf_kdl.cpp.o
  "KDL::Rotation::GetQuaternion(double&, double&, double&, double&) const", referenced from:
      tf::quaternionKDLToTF(KDL::Rotation const&, tf::Quaternion&) in tf_kdl.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [/Users/tlau/ros/devel_isolated/tf_conversions/lib/libtf_conversions.dylib] Error 1
make[1]: *** [CMakeFiles/tf_conversions.dir/all] Error 2
make: *** [all] Error 2
<== Failed to process package 'tf_conversions': 
  Command '/opt/ros/hydro/env.sh make -j4 -l4' returned non-zero exit status 2
```

I'm building according to [hydro installation instructions](http://wiki.ros.org/hydro/Installation/OSX/Homebrew/Source) on Mac OSX.

Any ideas?

### PR DESCRIPTION
**Pull request by tlau**
Fixes #45, as documented there.

### CODE REVIEW

**Comment by wjwwood** [comment]
Thanks @tlau for the pull request. This looks ok to me. +1

**Comment by wjwwood** [comment]
@tfoote for review

**Comment by tfoote** [comment]
Looks good to me.  @tlau Thanks for the patch! I'll test and release.

**Comment by tfoote** [comment]
Looks good to me. @tlau Thanks for the patch.

**Pull request merged**
